### ISSUE TITLE
Fatal error: Call to undefined function locale_get_default()

### ISSUE THREAD

**Issue by riwakawebsitedesigns** [gocart/GoCart#182]
I am just trying it out and came across couple issues after install it times it self out and also Fatal error: Call to undefined function locale_get_default() in C:\Xampp\htdocs\gocart\gocart\migrations\003_gocart2_3.php on line 252

**Comment by olimortimer** [comment]
Your server needs to have a default locale set - http://php.net/manual/bg/function.locale-get-default.php

You also need the php_intl extension installed. This is what's causing the locale_get_default error.
